name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Le workflow se déclenche à chaque push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifiez le code du repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Connectez-vous à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Connectez-vous à GitHub Packages
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extraction des métadonnées (tags, labels)
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/ue19-lab-05
            ghcr.io/${{ github.repository_owner }}/ue19-lab-05

      # Construisez et poussez l'image Docker
      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
