name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub and GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # Vérifiez le code du repository
      - name: Check out the repo
        uses: actions/checkout@v3

      # Connectez-vous à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Connectez-vous à GitHub Container Registry (GHCR)
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construisez l'image Docker et poussez-la vers Docker Hub et GitHub Packages
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ue19-lab-05:latest
            ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
