name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Vérifiez le code du repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurez Docker Buildx pour la construction multi-architecture
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connectez-vous à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Connectez-vous à GitHub Packages (GHCR)
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construisez l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ue19-lab-05:latest .

      # Publiez l'image sur Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ue19-lab-05:latest

      # Publiez l'image sur GitHub Packages
      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
